# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_sample.proto

require 'google/protobuf'


descriptor_data = "\n\x11\x61uth_sample.proto\x12\x0cgrpc.testing\"X\n\x07Request\x12#\n\rfill_username\x18\x04 \x01(\x08R\x0c\x66illUsername\x12(\n\x10\x66ill_oauth_scope\x18\x05 \x01(\x08R\x0e\x66illOauthScope\"G\n\x08Response\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\x12\x1f\n\x0boauth_scope\x18\x03 \x01(\tR\noauthScope2I\n\x0bTestService\x12:\n\tUnaryCall\x12\x15.grpc.testing.Request\x1a\x16.grpc.testing.ResponseBt\n\x10\x63om.grpc.testingB\x0f\x41uthSampleProtoP\x01\xa2\x02\x03GTX\xaa\x02\x0cGrpc.Testing\xca\x02\x0cGrpc\\Testing\xe2\x02\x18Grpc\\Testing\\GPBMetadata\xea\x02\rGrpc::Testingb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Grpc
  module Testing
    Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.testing.Request").msgclass
    Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.testing.Response").msgclass
  end
end
