# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hellostreamingworld.proto

require 'google/protobuf'


descriptor_data = "\n\x19hellostreamingworld.proto\x12\x13hellostreamingworld\"G\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12#\n\rnum_greetings\x18\x02 \x01(\tR\x0cnumGreetings\"&\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2b\n\x0cMultiGreeter\x12R\n\x08sayHello\x12!.hellostreamingworld.HelloRequest\x1a\x1f.hellostreamingworld.HelloReply\"\x00\x30\x01\x42\x9f\x01\n\x17\x63om.hellostreamingworldB\x18HellostreamingworldProtoP\x01\xa2\x02\x03HXX\xaa\x02\x13Hellostreamingworld\xca\x02\x13Hellostreamingworld\xe2\x02\x1fHellostreamingworld\\GPBMetadata\xea\x02\x13Hellostreamingworldb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hellostreamingworld
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hellostreamingworld.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hellostreamingworld.HelloReply").msgclass
end
