# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyvaluestore.proto

require 'google/protobuf'


descriptor_data = "\n\x13keyvaluestore.proto\x12\rkeyvaluestore\"\x1b\n\x07Request\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\" \n\x08Response\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value2S\n\rKeyValueStore\x12\x42\n\tGetValues\x12\x16.keyvaluestore.Request\x1a\x17.keyvaluestore.Response\"\x00(\x01\x30\x01\x42{\n\x11\x63om.keyvaluestoreB\x12KeyvaluestoreProtoP\x01\xa2\x02\x03KXX\xaa\x02\rKeyvaluestore\xca\x02\rKeyvaluestore\xe2\x02\x19Keyvaluestore\\GPBMetadata\xea\x02\rKeyvaluestoreb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Keyvaluestore
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("keyvaluestore.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("keyvaluestore.Response").msgclass
end
