# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: keyvaluestore.proto for package 'Keyvaluestore'
# Original file comments:
# Copyright 2018 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'keyvaluestore_pb'

module Keyvaluestore
  module KeyValueStore
    # A simple key-value storage service
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'keyvaluestore.KeyValueStore'

      # Provides a value for each key request
      rpc :GetValues, stream(::Keyvaluestore::Request), stream(::Keyvaluestore::Response)
    end

    Stub = Service.rpc_stub_class
  end
end
