# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

require 'google/protobuf'


descriptor_data = "\n\x11route_guide.proto\x12\nrouteguide\"A\n\x05Point\x12\x1a\n\x08latitude\x18\x01 \x01(\x05R\x08latitude\x12\x1c\n\tlongitude\x18\x02 \x01(\x05R\tlongitude\"Q\n\tRectangle\x12!\n\x02lo\x18\x01 \x01(\x0b\x32\x11.routeguide.PointR\x02lo\x12!\n\x02hi\x18\x02 \x01(\x0b\x32\x11.routeguide.PointR\x02hi\"L\n\x07\x46\x65\x61ture\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12-\n\x08location\x18\x02 \x01(\x0b\x32\x11.routeguide.PointR\x08location\"T\n\tRouteNote\x12-\n\x08location\x18\x01 \x01(\x0b\x32\x11.routeguide.PointR\x08location\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\"\x93\x01\n\x0cRouteSummary\x12\x1f\n\x0bpoint_count\x18\x01 \x01(\x05R\npointCount\x12#\n\rfeature_count\x18\x02 \x01(\x05R\x0c\x66\x65\x61tureCount\x12\x1a\n\x08\x64istance\x18\x03 \x01(\x05R\x08\x64istance\x12!\n\x0c\x65lapsed_time\x18\x04 \x01(\x05R\x0b\x65lapsedTime2\x85\x02\n\nRouteGuide\x12\x36\n\nGetFeature\x12\x11.routeguide.Point\x1a\x13.routeguide.Feature\"\x00\x12>\n\x0cListFeatures\x12\x15.routeguide.Rectangle\x1a\x13.routeguide.Feature\"\x00\x30\x01\x12>\n\x0bRecordRoute\x12\x11.routeguide.Point\x1a\x18.routeguide.RouteSummary\"\x00(\x01\x12?\n\tRouteChat\x12\x15.routeguide.RouteNote\x1a\x15.routeguide.RouteNote\"\x00(\x01\x30\x01\x42i\n\x0e\x63om.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RXX\xaa\x02\nRouteguide\xca\x02\nRouteguide\xe2\x02\x16Routeguide\\GPBMetadata\xea\x02\nRouteguideb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeguide
  Point = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Point").msgclass
  Rectangle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Rectangle").msgclass
  Feature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Feature").msgclass
  RouteNote = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.RouteNote").msgclass
  RouteSummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.RouteSummary").msgclass
end
